# Cấu hình dải mạng nội bộ
subnet 10.10.10.0 netmask 255.255.255.0 {
  range 10.10.10.10 10.10.10.100;
  option routers 10.10.10.1;
  option domain-name-servers 8.8.8.8;
}

# Máy Trung tâm
host central-server {
  hardware ethernet 00:0c:29:2f:33:71;
  fixed-address 10.10.10.45;
}

# Máy TeamVM
host team-vm {
  hardware ethernet 00:0c:29:77:8b:63;
  fixed-address 10.10.10.55;
}
